#!/bin/bash -eux

source $(dirname $(readlink -f $0))/try-vars

if [[ -r postbody ]]; then
  postbody=postbody
else
  postbody=-
fi

curl -s -H "Authorization: token $oauth_token" -X POST https://api.github.com/repos/$repo/statuses/$sha1 -d @$postbody
